/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpus;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author My PC
 */
public class DataPeminjaman extends javax.swing.JFrame {

    /**
     * Creates new form DataPeminjaman
     */
    String sql = "select * from peminjaman";
    
    public DataPeminjaman() {
        initComponents();
        showTable(sql);
        tampil();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtJumlahPeminjam = new javax.swing.JTextField();
        btnCariPeminjaman = new javax.swing.JButton();
        btnHapusPeminjaman = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtTableDataPeminjaman = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNamaPeminjam = new javax.swing.JTextField();
        btnKembali = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtIdPeminjaman = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtIdAnggota = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNamaPeminjam1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        NamaBuku = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        txtTglPeminjaman = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        txtTglPengembalian = new com.toedter.calendar.JDateChooser();
        btnUpdate = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));

        txtJumlahPeminjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahPeminjamActionPerformed(evt);
            }
        });

        btnCariPeminjaman.setText("CARI");
        btnCariPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariPeminjamanActionPerformed(evt);
            }
        });

        btnHapusPeminjaman.setText(" HAPUS PENCARIAN");
        btnHapusPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusPeminjamanActionPerformed(evt);
            }
        });

        txtTableDataPeminjaman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Peminjaman", "ID Anggota", "Nama Peminjam", "Nama Buku", "Tanggal Peminjaman", "Tanggal Pengembalian"
            }
        ));
        txtTableDataPeminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTableDataPeminjamanMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(txtTableDataPeminjaman);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("DATA PEMINJAMAN");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Jumlah Peminjam");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nama Peminjam");

        txtNamaPeminjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaPeminjamActionPerformed(evt);
            }
        });

        btnKembali.setText("KEMBALI");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("ID Peminjaman");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ID Anggota");

        txtIdAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdAnggotaActionPerformed(evt);
            }
        });
        txtIdAnggota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIdAnggotaKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama Peminjam");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nama Buku");

        NamaBuku.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "----------------------- Pilih -----------------------" }));
        NamaBuku.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        NamaBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaBukuActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Tanggal Peminjaman");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tanggal Pengembalian");

        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(396, 396, 396))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTglPeminjaman, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NamaBuku, 0, 300, Short.MAX_VALUE)
                            .addComponent(txtNamaPeminjam1)
                            .addComponent(txtIdAnggota)
                            .addComponent(txtIdPeminjaman)
                            .addComponent(txtTglPengembalian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(346, 346, 346)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNamaPeminjam, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                            .addComponent(txtJumlahPeminjam))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCariPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHapusPeminjaman))
                        .addGap(297, 297, 297))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtNamaPeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCariPeminjaman))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtJumlahPeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapusPeminjaman))
                .addGap(44, 44, 44)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamaPeminjam1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NamaBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtTglPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtTglPengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnKembali)
                                .addComponent(btnUpdate)
                                .addComponent(btnHapus))))
                    .addComponent(jLabel12))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void showTable(String sql) {
        // Fungsi try-catch untuk mengurung eksekusi yang menampilkan error dan dapat membuat program tetap berjalan tanpa dihentikan secara langsung
        try {
            Statement stat = (Statement)KoneksiDb.ConnectDatabase().createStatement();
            ResultSet rs = stat.executeQuery(sql); //untuk mengembalikan objek ResultSet
            DefaultTableModel tableModel = (DefaultTableModel)txtTableDataPeminjaman.getModel();
            tableModel.getDataVector().removeAllElements(); //berfungsi untuk menghapus data sebelumnya dan membuat data baru yang ada di while
            while(rs.next()){
                tableModel.addRow(new Object[] {
                    rs.getString(1), rs.getString(2), 
                    rs.getString(3), rs.getString(4),
                    rs.getString(5), rs.getString(6)
                });
                
                int jumlahPeminjam;
                jumlahPeminjam = rs.getRow();              
                txtJumlahPeminjam.setText("" + jumlahPeminjam);
            }
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(DataPeminjaman.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void tampil(){
        try{
          String sql = "Select * From buku";
          Statement stat = (Statement)KoneksiDb.ConnectDatabase().createStatement();
          ResultSet rs = stat.executeQuery(sql); //untuk mengembalikan objek ResultSet
          
          while(rs.next()){
              NamaBuku.addItem(rs.getString("Nama_Buku"));
          }
          
          rs.last();
          int jumlahdata = rs.getRow();
          rs.first();
        } catch(Exception e){
            
        }
        
    }
    
    private void txtJumlahPeminjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahPeminjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahPeminjamActionPerformed

    private void btnCariPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariPeminjamanActionPerformed
        if(txtNamaPeminjam.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Pilih Data Yang Ingin Dicari", "Error", JOptionPane.ERROR_MESSAGE);
            showTable(sql);
        } else {
            showTable("SELECT * FROM peminjaman WHERE Nama_Peminjam LIKE '%"
                    + txtNamaPeminjam.getText() +  "%'");
        }
    }//GEN-LAST:event_btnCariPeminjamanActionPerformed

    private void btnHapusPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusPeminjamanActionPerformed
        txtNamaPeminjam.setText("");
        showTable(sql);
    }//GEN-LAST:event_btnHapusPeminjamanActionPerformed

    private void txtTableDataPeminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTableDataPeminjamanMouseClicked
        int i = txtTableDataPeminjaman.getSelectedRow();
        DefaultTableModel tableModel = (DefaultTableModel)txtTableDataPeminjaman.getModel();
        
        try {
            if(i > -1){
            Date date = new SimpleDateFormat("yyyy-MM-dd").parse((String)tableModel.getValueAt(i, 4).toString());
            Date date2 = new SimpleDateFormat("yyyy-MM-dd").parse((String)tableModel.getValueAt(i, 5).toString());
            txtIdPeminjaman.setText(tableModel.getValueAt(i, 0).toString());
            txtIdAnggota.setText(tableModel.getValueAt(i, 1).toString());
            txtNamaPeminjam1.setText(tableModel.getValueAt(i, 2).toString());
            NamaBuku.setSelectedItem(tableModel.getValueAt(i, 3).toString());
            txtTglPeminjaman.setDate(date);
            txtTglPengembalian.setDate(date2);
            }
        } catch (ParseException ex) {
            Logger.getLogger(DataPeminjaman.class.getName()).log(Level.SEVERE, null, ex);
        }   
    }//GEN-LAST:event_txtTableDataPeminjamanMouseClicked

    private void txtNamaPeminjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaPeminjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaPeminjamActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        MenuPustakawan mn = new MenuPustakawan();
        int response = JOptionPane.showConfirmDialog(this, "Apakah Anda Yakin ?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(response == JOptionPane.YES_OPTION){
            mn.setVisible(true);
            this.dispose();
        } else{
            
        }
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void txtIdAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdAnggotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdAnggotaActionPerformed

    private void txtIdAnggotaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdAnggotaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdAnggotaKeyReleased

    private void NamaBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaBukuActionPerformed

    }//GEN-LAST:event_NamaBukuActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int i = txtTableDataPeminjaman.getSelectedRow();
        DefaultTableModel tableModel = (DefaultTableModel)txtTableDataPeminjaman.getModel();
        if(i == -1){
            return;
        }
        String tampilan = "yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        String tanggal = String.valueOf(fm.format(txtTglPeminjaman.getDate()));
        
        String tampilan2 = "yyyy-MM-dd";
        SimpleDateFormat fm2 = new SimpleDateFormat(tampilan2);
        String tanggal2 = String.valueOf(fm2.format(txtTglPengembalian.getDate()));
        
        String idPeminjam = txtIdPeminjaman.getText();
        String idAnggota = txtIdAnggota.getText();
        String namaPeminjam = txtNamaPeminjam1.getText();
        String namaBuku = (String)NamaBuku.getSelectedItem();
        String tglPeminjaman = tanggal;
        String tglPengembalian = tanggal2;
        
        try {
            Connection conn = (Connection)KoneksiDb.ConnectDatabase();
            String sql = "update peminjaman set ID_Anggota = ?, Nama_Peminjam = ?, Nama_Buku = ?, Tgl_Peminjaman = ?, Tgl_Pengembalian = ? where ID_Peminjaman = ?";
            PreparedStatement pst = (PreparedStatement) conn.prepareStatement(sql);
            pst.setString(1, idAnggota);
            pst.setString(2, namaPeminjam);
            pst.setString(3, namaBuku);
            pst.setString(4, tglPeminjaman);
            pst.setString(5, tglPengembalian);
            pst.setString(6, idPeminjam);
            
            pst.executeUpdate();
            pst.close();
            JOptionPane.showMessageDialog(null, "Data Berhasil di Ubah");
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(Peminjaman.class.getName()).log(Level.SEVERE, null, ex);
        } finally{
            showTable(sql);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        int i = txtTableDataPeminjaman.getSelectedRow();
        DefaultTableModel tableModel = (DefaultTableModel)txtTableDataPeminjaman.getModel();
        if(i == -1){
            return;
        }
        String id = (String)tableModel.getValueAt(i, 0);

        int question = JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin Ingin Menghapus Data Ini?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(question == JOptionPane.OK_OPTION){
            try {
                Connection conn = (Connection)KoneksiDb.ConnectDatabase();
                String sql = "delete from peminjaman WHERE ID_Peminjaman = ?";
                PreparedStatement pst = (PreparedStatement) conn.prepareStatement(sql);
                pst.setString(1, id);
                pst.executeUpdate();
                pst.close();
                JOptionPane.showMessageDialog(null, "Data Berhasil Terhapus");
            } catch (SQLException ex) {
                java.util.logging.Logger.getLogger(Peminjaman.class.getName()).log(Level.SEVERE, null, ex);
            } finally{
                showTable(sql);
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataPeminjaman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox NamaBuku;
    private javax.swing.JButton btnCariPeminjaman;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnHapusPeminjaman;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtIdAnggota;
    private javax.swing.JTextField txtIdPeminjaman;
    private javax.swing.JTextField txtJumlahPeminjam;
    private javax.swing.JTextField txtNamaPeminjam;
    private javax.swing.JTextField txtNamaPeminjam1;
    private javax.swing.JTable txtTableDataPeminjaman;
    private com.toedter.calendar.JDateChooser txtTglPeminjaman;
    private com.toedter.calendar.JDateChooser txtTglPengembalian;
    // End of variables declaration//GEN-END:variables
}
